# Generated by Django 4.1.7 on 2023-03-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_account_initial_deposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initial_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
